title: Food & Drinks
author:
  name:
  email: "foodanddrinks@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Nuestro objetivo es acercar la gran cocina a un mayor número de personas, haciendo que el precio de venta fuera accesible a una gran mayoría, y lo hemos coseguido gracias a tu preferencia.

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
include: ["_pages"]

bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  #header_pages:
  # - about.md

  # generate social links in footer
  social_links:
    twitter: "https://twitter.com/alvarado0501"
    github: "https://github.com/camilo78"
    #facebook: 'https://example.com/@jekyllrb'
    #instagram: 'https://example.com/@jekyllrb'
    #linkedin: 'https://example.com/@jekyllrb'
    #google: 'https://example.com/@jekyllrb'
    #youtube: 'https://example.com/@jekyllrb'
    #twitch: 'https://example.com/@jekyllrb'
    #telegram: 'https://example.com/@jekyllrb'
    #whatsapp: 'https://example.com/@jekyllrb'
    #discord: 'https://example.com/@jekyllrb'
    #slack: 'https://example.com/@jekyllrb'

# Build settings
theme: jekyll-bootstrap-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
